name: Release

on:
  push:
    tags:
      - "rc*.*.*"
    
jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
    # 检出仓库
    - uses: actions/checkout@v3
    # 设置环境
    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: 1.20.3
    # 发布应用包
    - name: Build go binaries
      run: make release
    # 创建release
    - uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: 'bin/*'